# Generated by Django 4.2.6 on 2023-11-04 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Village', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20, unique=True)),
                ('Gmail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('Photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TailorFlow.customers')),
                ('Neck', models.FloatField(blank=True, null=True)),
                ('Chest', models.FloatField(blank=True, null=True)),
                ('Waist', models.FloatField(blank=True, null=True)),
                ('Hips', models.FloatField(blank=True, null=True)),
                ('Thigh', models.FloatField(blank=True, null=True)),
                ('Knee', models.FloatField(blank=True, null=True)),
                ('Calf', models.FloatField(blank=True, null=True)),
                ('Sleeve', models.FloatField(blank=True, null=True)),
                ('Back', models.FloatField(blank=True, null=True)),
                ('Waistband', models.FloatField(blank=True, null=True)),
                ('Outseam', models.FloatField(blank=True, null=True)),
                ('Inseam', models.FloatField(blank=True, null=True)),
                ('Ankle', models.FloatField(blank=True, null=True)),
                ('Height', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailorFlow.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('garment_drop_off', models.DateTimeField()),
                ('requested_pick_up_date', models.DateField()),
                ('garment_pick_up', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TailorFlow.customers')),
            ],
        ),
    ]
