# Generated by Django 4.2.6 on 2023-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0005_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='clothimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
