# Generated by Django 4.2.6 on 2023-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0008_customers_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
