# Generated by Django 4.2.7 on 2023-12-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0013_alter_customers_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='profilephoto',
            field=models.ImageField(default='', upload_to='images/profilephotos'),
        ),
    ]
