# Generated by Django 4.2.6 on 2023-11-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0002_remove_customers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='garment_drop_off',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='garment_pick_up',
            field=models.DateField(blank=True, null=True),
        ),
    ]
