# Generated by Django 4.2.6 on 2023-11-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0003_alter_products_garment_drop_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='Height',
        ),
    ]
