# Generated by Django 4.2.6 on 2023-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0006_products_clothimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='design',
            field=models.ImageField(default='', upload_to='images/design'),
        ),
        migrations.AlterField(
            model_name='products',
            name='clothimage',
            field=models.ImageField(default='', upload_to='images/clothimages'),
        ),
    ]
