# Generated by Django 4.2.6 on 2023-11-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0007_products_design_alter_products_clothimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profilephoto',
            field=models.ImageField(default='', upload_to='images/profilephotos'),
        ),
    ]
