# Generated by Django 4.2.6 on 2023-12-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorFlow', '0015_customers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_stitched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(default='', editable=False),
        ),
    ]
